on: [push, pull_request]

name: Nim testing and linting

jobs:
  nim-test:
    name: Run Nim tests using `nimble test`

    strategy:
      max-parallel: 3
      matrix:
        os: [ubuntu-22.04, windows-latest, macos-12]
    runs-on: ${{ matrix.os }}

    continue-on-error: true

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3
      - uses: iffy/install-nim@v4.1.3
        with:
          version: binary:1.6.6
      - run: nimble install --depsOnly --accept
      - run: nimble test

  nim-lint:
    name: Lint Nim code

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - uses: reviewdog/action-nimlint@v1.7.0
        with:
          github_token: ${{ secrets.github_token }}
          src: 'src/**/*.nim'
